on:
  push:
    branches:
      - 'main'

env:
  APP_LOCATION: '/'
  APP_ARTIFACT_LOCATION: 'dist'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "gct-keyvault-dev"
          secrets: 'gct-web-api-token-secret' 
        id: GetSecrets
      
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.GetSecrets.outputs.gct-web-api-token-secret }}
          action: 'upload'
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
